name: Wheather APP CI

on:
    push:
     branches: [main]
    pull_request:
        types : [labeled, opened]


jobs:
    build:
        if: |
            github.event_name == 'push' || 
            contains(github.event.pull_request.labels.*.name, 'ready-to-test')
        
        runs-on: ubuntu-latest

        steps:
           - name: 1.Checkout Code
             uses: actions/checkout@v4
             
           - name: 2. Setup Node
             uses: actions/setup-node@v4
             with:
                node-version: '20'
                cache: 'npm'
           - name: 3. Install Dependencies
             run: npm ci
             
           - name: 4. Run tests
             run: npm test
             env:
                WEATHER_API_KEY: ${{secrets.WEATHER_API_KEY}}



    


